services:
  mongodb:
    image: mongo:latest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]


  backend:
    image: karankumarmishra/skybox_backend:latest
    ports:
      - "88:88"
      - "27017:27017"
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - .env.backend
     
 


  frontend:
    image:  karankumarmishra/skybox_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env.frontend

# volumes:
#   redis_data:
#   mongodb_data:

networks:
  app-network:
    driver: bridge