# Entry points configuration
entryPoints:
  hoststream-network:
    address: ":80"
  websecure:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.Skybox.localhost`)"
    network: hoststream-network  # Important for container communication

# API and dashboard configuration
api:
  insecure: true
  dashboard: true